### ISSUE TITLE
Encoding::UndefinedConversionError ("\xE2" from ASCII-8BIT to UTF-8)

### ISSUE THREAD

**Issue by tae8838** [bensheldon/good_job#198] opened 2021-01-15 10:41 UTC
I am trying to enqueue a mailer job with attached pdf and I got this error. It was working when I was using delayed_job. We are trying to switch to good_job because it supports jruby.

I ran `wtf?` on my pry and got this trace:
```
Exception: Encoding::UndefinedConversionError: "\xE2" from ASCII-8BIT to UTF-8
--
0: org/jruby/RubyString.java:6225:in `encode'
1: json/ext/GeneratorMethods.java:105:in `to_json'
2: /Users/tae/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-6.1.1/lib/active_support/core_ext/object/json.rb:40:in `to_json'
3: /Users/tae/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:57:in `to_json'
4: json/ext/GeneratorState.java:209:in `generate'
5: /Users/tae/.rbenv/versions/jruby-9.2.11.1/lib/ruby/stdlib/json/common.rb:224:in `generate'
6: /Users/tae/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:110:in `stringify'
7: /Users/tae/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:35:in `encode'
8: /Users/tae/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activesupport-6.1.1/lib/active_support/json/encoding.rb:22:in `encode'
9: /Users/tae/.rbenv/versions/jruby-9.2.11.1/lib/ruby/gems/shared/gems/activerecord-6.1.1/lib/active_record/type/json.rb:18:in `serialize'
```

I'm still looking into this issue. Will update if I figure anything else out.
Thank you!

**Comment by bensheldon** [comment] 2021-01-15 16:31
Thanks for trying out GoodJob!

It looks like maybe when the ActiveJob/ActionMailer params are serialized into JSON to be stored in the database for GoodJob, there is an encoding issue.

Could you share the code you're invoking that triggers this error? I'd like to understand how the PDF is attached.

**Comment by slimdave** [comment] 2021-01-15 21:10
FWIW I have seen similar errors when reading from files (actually when using `Paperclip.io_adaptors.for(attachment).read`) and I think the issue is an assumption that the data is ASCII, which was fixed by appending `force_encoding("UTF-8")` to the method chain. Hope this helps.

**Comment by headius** [comment] 2021-01-15 21:30
Make sure you are running latest JRuby and the json gem... I think there have been some encoding fixes over the past year or so.

**Comment by tae8838** [comment] 2021-01-19 03:38
Thanks for the comments. I worked around this by using the object in the params and query for the file in the mailer.

Not sure if anyone else wants to look into this but the code I used was something like this:

```
files = PurchaseOrder.where(active: true).map { |po| { content: po.po_file.blob.download, name: "#{po.purchase_order_number}.pdf" } }

MyMailer.send_email(to_emails, to_emails, files).deliver_later
```

**Closed** 2021-08-02 14:55 UTC
