### ISSUE TITLE
Bulk reschedule and discard jobs via dashboard

### ISSUE THREAD

**Issue by danielwestendorf** [bensheldon/good_job#527] opened 2022-02-20 20:59 UTC
Sometimes it us useful to select N queued jobs and either reschedule or discard them via the dashboard.

Ideally this would include checkboxes to select the jobs displayed, a "Discard Selected" and "Reschedule Selected" buttons, which submit the selected jobs for the appropriate action.

Building upon this further, a "Discard All" and "Reschedule All" buttons may make sense too.

I'd be happy to implement this if it belongs in the project.

**Comment by bensheldon** [comment] 2022-02-20 23:20
@danielwestendorf your contribution would be appreciated! 🙏

I'm going to close this as a dupe of #446.

**Closed** 2022-02-20 23:20 UTC
