### ISSUE TITLE
Is there a way to show how many worker/process is running currently

### ISSUE THREAD

**Issue by v9n** [bensheldon/good_job#471] opened 2021-12-18 23:54 UTC
I would love to have a way to show current worker/process. With our user of Postgres we can store lot more useful information. worker name, host name etc will be great.

Will happy to explorer this and make a PR if the team consider this feature is useful.

**Comment by bensheldon** [comment] 2021-12-19 02:41
@v9n awesome! I already have this in mind (#421), and I'd love your help. It would be really helpful if you help concretely define some minimum requirements for the information that you would like to see displayed about the worker/process.

I will close this as a duplicate of #421 and let's continue the discussion over there.

**Closed** 2021-12-19 03:09 UTC
